var namespaces =
[
    [ "assert", "d2/dab/namespaceassert.html", null ],
    [ "collection", "d7/d82/namespacecollection.html", null ],
    [ "console", "dc/daa/namespaceconsole.html", null ],
    [ "coroutine", "d6/d05/namespacecoroutine.html", null ],
    [ "crypto", "de/d36/namespacecrypto.html", null ],
    [ "db", "d0/d45/namespacedb.html", null ],
    [ "encoding", "db/da8/namespaceencoding.html", null ],
    [ "fs", "d5/d8f/namespacefs.html", null ],
    [ "gd", "dd/d5d/namespacegd.html", null ],
    [ "global", "d4/dfd/namespaceglobal.html", null ],
    [ "hash", "de/de9/namespacehash.html", null ],
    [ "http", "d3/d69/namespacehttp.html", null ],
    [ "io", "d1/d96/namespaceio.html", null ],
    [ "mq", "dd/dbd/namespacemq.html", null ],
    [ "net", "dc/d27/namespacenet.html", null ],
    [ "os", "da/de1/namespaceos.html", null ],
    [ "path", "d0/d43/namespacepath.html", null ],
    [ "process", "d8/d25/namespaceprocess.html", null ],
    [ "profiler", "dc/dfc/namespaceprofiler.html", null ],
    [ "re", "d5/d83/namespacere.html", null ],
    [ "rpc", "d0/d14/namespacerpc.html", null ],
    [ "ssl", "df/dd2/namespacessl.html", null ],
    [ "test", "df/d04/namespacetest.html", null ],
    [ "util", "d6/d72/namespaceutil.html", null ],
    [ "uuid", "d1/dd6/namespaceuuid.html", null ],
    [ "vm", "d8/d89/namespacevm.html", null ],
    [ "xml", "d8/dd3/namespacexml.html", null ],
    [ "zlib", "d9/d3e/namespacezlib.html", null ]
];