/*! @brief 消息处理器异步等待对象
    @brief Message Handler object for asynchronous waiting
 */
interface AsyncWait: Handler
{
    /*! @brief 结束等待，继续处理消息 */
    /*! @brief Finish waiting, moving on to handle the message */
    end();
};
