
/*! @brief 包含 multipart 的一个条目数据
    @brief a data item that contains multipart
*/
interface HttpUploadData : object
{
    /*! @brief 包含本条目数据的文件名
        @brief file name of the data item
    */
    readonly String fileName;

    /*! @brief 包含本条目数据的类型
        @brief content type of the data item
    */
    readonly String contentType;

    /*! @brief 包含本条目数据的传输编码类型
        @brief content transfer encoding of the data item
    */
    readonly String contentTransferEncoding;

    /*! @brief 包含本条目数据部分的流对象
        @brief stream object of the data item
    */
    readonly SeekableStream body;
};
