/*! @brief base object for all other objects */
interface object
{
    /*! @brief force garbadge collection on object，once called，all its memory will be release*/
    dispose();

    /*! @brief return object in string type，e.g. "[Native Object]"，object can overwrite this behavior based on user defined cases
     @return return obejct in string type
    */
    String toString();

    /*! @brief return object in JSON， by default should return a JSON object with all obejct attributes as key and value 
     @param key "unused"
     @return return all JSON serielizable keys
     */
    Value toJSON(String key = "");

    /*! @brief return value of obejct itself
     @return return value of obejct itself
    */
    Value valueOf();
};

