
/*! @brief Packet protocal converter

  Used for convert data stream to Packet protocol message, to create:
  @code
  var pkghdlr = new mq.PacketHandler(...);
  @endcode
 */
interface PacketHandler: Handler
{
    /*! @brief Packet constructor
     @param hdlr Builtin message handler, handle function or javascript message mapping object, see mq.jsHandler
     */
    PacketHandler(Value hdlr);

    /*! @brief Get and set maximum packet size in MB, default is 64 */
    Integer maxSize;

    /*! @brief Packet protocol converter current handle interface object */
    Handler handler;

    /*! @brief Get Packet protocol handler working status

      Return Stats object as follows:
      @code
      {
          total : 1000,    // Totoal handled requests
          pendding : 100,  // Pendding requests to handle
          request : 10,    // New requests
          response : 10,   // Responsed requests
          error : 100      // Error count
      }
      @endcode
     */
    readonly Stats stats;
};
