
/*! @brief Packet handler  */
interface PacketMessage: Message
{
    /*! @brief Packet handler constructor
    @param maxSize Maximum packet size in MB, defualt is 67108864(64M)
     */
    PacketMessage(Integer maxSize = 67108864);

    /*! @brief Get and set maximum packet size in bytes, default is 67108864(64M) */
    Integer maxSize;
};
