/*! @brief process manage module, manage current resource used by current process

 how to use
 @code
 var process = require('process');
 @endcode
 */
module process
{
    /*! @brief return current process command line args*/
    static readonly Array argv;

    /*! @brief check current exec file full path*/
    static readonly String execPath;

    /*! @brief exit current process and return result
     @param code return process result
     */
    static exit(Integer code);

    /*! @brief return current working directory
     @return current working directory
     */
    static String cwd();

    /*! @brief change current working directory
     @param directory target working directory
     */
    static chdir(String directory);

    /*! @brief check current memory usage log
     @return return memory usage log

     memory usage log output example:
     @code
     {
       "rss": 8622080,
       "heapTotal": 4083456,
       "heapUsed": 1621800
     }
     @endcode
    note: 
     - rss return physical memory used by current process
     - heapTotal return total memory used by V8 engine
     - heapUsed return heap memory used by v8 engine
     */
    static Object memoryUsage();

    /*! @brief exec command，return result from cmd
     @param cmd command
     @return result
     */
    static Integer system(String cmd) async;

    /*! @brief exec command，and access result
     @param cmd command
     @return return file with result from cmd
     */
    static BufferedStream popen(String cmd) async;

    /*! @brief exec command and return after finish
     @param cmd command
     */
    static exec(String cmd);
};
