/*! @brief Process handle module, to manage current process resources

 To use it:
 @code
 var process = require('process');
 @endcode
 */
module process
{
    /*! @brief Get commnad line arguments */
    static readonly Array argv;

    /*! @brief Get full execution path */
    static readonly String execPath;

    /*! @brief Exit current process with code
     @param code Return process code
     */
    static exit(Integer code);

    /*! @brief Get work directory path
     @return Return work directory path
     */
    static String cwd();

    /*! @brief Change work directory path
     @param directory New work directory path
     */
    static chdir(String directory);

    /*! @brief Get process memory usage
     @return Return memory usage

     Usage includes:
     @code
     {
       "rss": 8622080,
       "heapTotal": 4083456,
       "heapUsed": 1621800
     }
     @endcode
     Notes:
     - rss Physical memory being occupied by current process
     - heapTotal Return v8 engine heap memory size
     - heapUsed Return v8 engine heap memory size in use
     */
    static Object memoryUsage();

    /*! @brief Execute commnad and return results
     @param cmd Command to run
     @return Return execution results
     */
    static Integer system(String cmd) async;

    /*! @brief Execute commnad and get access to results
     @param cmd Command to run
     @return Return file contains execution results
     */
    static BufferedStream popen(String cmd) async;

    /*! @brief Execute command and return immediately
     @param cmd Command to run
     */
    static exec(String cmd);
};
