
/*! @brief Memory profiler module

 The way to use:
 @code
 var profiler = require('profiler');
 @endcode
 */
module profiler
{
    /*! @brief Get the current HeapSnapshot, HeapSnapshots record the state of the JS heap at some moment.
     @return Returns the acquired HeapSnapshots.
     */
	static HeapSnapshot takeSnapshot();

	/*! @brief Delete all HeapSnapshots.
    */
	static DeleteAllHeapSnapshots();
};
