
/*! @brief regular expression module */
module re
{
    /*! @brief compile a regex template and return a regex module object
     @param pattern regex parttern
     @param opt defined match type. "g" for global match，"i" for uppercase and lower case match, "gi" for global uppercase and lowercase match
     @return regex obejct
     */
    static Regex compile(String pattern, String opt = "");
};
