
/*! @brief remote procedure call, calling message transfer module

 How to use：
 @code
 var rpc = require('rpc');
 @endcode
 */
module rpc
{
    /*! @brief create a json-rpc message transfer processor
     @param hdlr embeded message transfer processor，callback function，or javascript message mapping object:，for detail, reference mq.jsHandler
     @return new message transfer processor
     */
    static Handler json(Value hdlr);
};
